### PR TITLE
Users can now send additional parameters to the template

### PR DESCRIPTION
**Pull request by mascip**
Hi Jesse, about 10 characters added. We can now do
<code>
route '/' => 'view.template', ( template => 'index.tt', some_param => 'nice :-)' , other => 'stuff' );  
</code>

### CODE REVIEW

**Comment by mascip** [comment]
Oh sorry that was wrong, I just understood my mistake.
This hash is not a parameter to view.template(), but to the OX::RouteBuilder. It provides validation and default values. I provided it with default values which were integrated to $r->mapping, so that it was used in view.template() in the end. So it works if I pass some Strings. But if I try to pass an ArrayRef, then the RouteBuilder doesn't like it at all: it doesn't look like a validator nor a default.

Then, how could we pass these parameters to the View, who would pass it to Template->process()? The view could have an optional "template_params" attribute. How does this sound? 

I'm happy to send a pull request if you like the idea. But I might do go on an internet-free 3 weeks holidays from tomorrow.

**Comment by mascip** [comment]
Done. If you like it we will need to add documentation.

I hope I didn't miss a simpler way to do this with the existing code (^c^). Learning OX is fun!

**Comment by doy** [comment]
Yeah, the second commit looks good to me. Can you remove the first commit and add some tests and documentation? I'll merge it once that's done.

**Comment by doy** [comment]
Any updates on this?

**Comment by mascip** [comment]
I don't use it anymore, but I'd still like to contribute it.

I'm too busy to work on this in the next 4 weeks (most hectic time of the
year). I'm putting it in my calendar after that.

**Comment by mascip** [comment]
I added a test, documentation, and squashed the commits. Let me know if it's all good :)

**Comment by doy** [comment]
Thanks!

**Comment by mascip** [comment]
Nice, happy to have contributed :)

**Pull request merged**
